<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HRISSeeder extends Seeder
{
    public function run(): void
    {
        // --- Companies ---
        $companies = [
            ['name' => 'Tom N Toms', 'industry' => 'Coffee Shop', 'has_account' => false],        
            ['name' => 'TechHub', 'industry' => 'Call Center', 'has_account' => true],          
            ['name' => 'SteamTrain', 'industry' => 'Coffee Shop', 'has_account' => false],      
        ];

        DB::table('companies')->insert($companies);

        $companyIds = DB::table('companies')->pluck('company_id', 'name');

        // --- Departments ---
        $departments = [
            ['company_id' => $companyIds['Tom N Toms'], 'name' => 'Barista Team'],
            ['company_id' => $companyIds['Tom N Toms'], 'name' => 'Cashier Team'],
            ['company_id' => $companyIds['TechHub'], 'name' => 'Customer Support'],
            ['company_id' => $companyIds['TechHub'], 'name' => 'IT'],
            ['company_id' => $companyIds['SteamTrain'], 'name' => 'Barista Team'],
        ];
        DB::table('departments')->insert($departments);

        $departmentIds = DB::table('departments')->pluck('department_id', 'name');

        // --- Positions ---
        $positions = [
            ['company_id' => $companyIds['Tom N Toms'], 'title' => 'Barista'],
            ['company_id' => $companyIds['Tom N Toms'], 'title' => 'Cashier'],
            ['company_id' => $companyIds['TechHub'], 'title' => 'CSR'],
            ['company_id' => $companyIds['TechHub'], 'title' => 'Team Lead'],
            ['company_id' => $companyIds['SteamTrain'], 'title' => 'Barista'],
        ];
        DB::table('positions')->insert($positions);

        $positionIds = DB::table('positions')->pluck('position_id', 'title');

        // --- Accounts (for TechHub only) ---
        $accounts = [
            ['company_id' => $companyIds['TechHub'], 'name' => 'Amazon Support', 'active' => true],
            ['company_id' => $companyIds['TechHub'], 'name' => 'eBay Escalations', 'active' => true],
        ];
        DB::table('accounts')->insert($accounts);

        $accountIds = DB::table('accounts')->pluck('account_id', 'name');

        // --- Employees (60 total - distributed across companies) ---
        $employees = [
            // Tom N Toms (20 employees)
            [
                'id_number' => 'TNT001', 'last_name' => 'Ando', 'first_name' => 'Francelyn',
                'middle_name' => 'A.', 'gender' => 'Female', 'birth_date' => '1996-05-10',
                'age' => 29, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09171234567', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '11-2222-3333', 'phic_number' => 'PH123456', 'hdmf_number' => 'HDMF123456',
                'tin_number' => 'TIN123456', 'date_hired' => '2022-01-15',
                'date_regularized' => '2022-07-15', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT002', 'last_name' => 'Atillo', 'first_name' => 'David',
                'middle_name' => 'B.', 'gender' => 'Male', 'birth_date' => '1995-11-20',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Tagum City',
                'contact_number' => '09182345678', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '22-3333-4444', 'phic_number' => 'PH654321', 'hdmf_number' => 'HDMF654321',
                'tin_number' => 'TIN654321', 'date_hired' => '2021-06-01',
                'date_regularized' => '2021-12-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT003', 'last_name' => 'Amigo', 'first_name' => 'Marlita',
                'middle_name' => 'C.', 'gender' => 'Female', 'birth_date' => '1998-09-12',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09193456789', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '33-4444-5555', 'phic_number' => 'PH789123', 'hdmf_number' => 'HDMF789123',
                'tin_number' => 'TIN789123', 'date_hired' => '2023-03-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT004', 'last_name' => 'Babida', 'first_name' => 'Jill',
                'middle_name' => 'D.', 'gender' => 'Female', 'birth_date' => '1997-04-15',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09194567890', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '44-5555-6666', 'phic_number' => 'PH111222', 'hdmf_number' => 'HDMF111222',
                'tin_number' => 'TIN111222', 'date_hired' => '2022-02-01',
                'date_regularized' => '2022-08-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT005', 'last_name' => 'Caminade', 'first_name' => 'Erika',
                'middle_name' => 'E.', 'gender' => 'Female', 'birth_date' => '1996-08-22',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09195678901', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '55-6666-7777', 'phic_number' => 'PH222333', 'hdmf_number' => 'HDMF222333',
                'tin_number' => 'TIN222333', 'date_hired' => '2021-09-01',
                'date_regularized' => '2022-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT006', 'last_name' => 'Cantere', 'first_name' => 'Charlotte',
                'middle_name' => 'F.', 'gender' => 'Female', 'birth_date' => '1999-01-10',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09196789012', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '66-7777-8888', 'phic_number' => 'PH333444', 'hdmf_number' => 'HDMF333444',
                'tin_number' => 'TIN333444', 'date_hired' => '2023-01-15',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT007', 'last_name' => 'De Lara', 'first_name' => 'Norielyn',
                'middle_name' => 'G.', 'gender' => 'Female', 'birth_date' => '1995-06-18',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Tagum City',
                'contact_number' => '09197890123', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '77-8888-9999', 'phic_number' => 'PH444555', 'hdmf_number' => 'HDMF444555',
                'tin_number' => 'TIN444555', 'date_hired' => '2020-05-01',
                'date_regularized' => '2020-11-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT008', 'last_name' => 'Ditomal', 'first_name' => 'Carding',
                'middle_name' => 'H.', 'gender' => 'Male', 'birth_date' => '1994-03-25',
                'age' => 31, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09198901234', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '88-9999-0000', 'phic_number' => 'PH555666', 'hdmf_number' => 'HDMF555666',
                'tin_number' => 'TIN555666', 'date_hired' => '2021-07-01',
                'date_regularized' => '2022-01-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT009', 'last_name' => 'Jamilla', 'first_name' => 'Aldrine Jason',
                'middle_name' => 'I.', 'gender' => 'Male', 'birth_date' => '1997-12-05',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09199012345', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '99-0000-1111', 'phic_number' => 'PH666777', 'hdmf_number' => 'HDMF666777',
                'tin_number' => 'TIN666777', 'date_hired' => '2022-04-01',
                'date_regularized' => '2022-10-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT010', 'last_name' => 'Labos', 'first_name' => 'Joanna Jean',
                'middle_name' => 'J.', 'gender' => 'Female', 'birth_date' => '1998-07-14',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09190123456', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '10-1111-2222', 'phic_number' => 'PH777888', 'hdmf_number' => 'HDMF777888',
                'tin_number' => 'TIN777888', 'date_hired' => '2023-02-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT011', 'last_name' => 'Magtaas', 'first_name' => 'Joshua Renzo',
                'middle_name' => 'K.', 'gender' => 'Male', 'birth_date' => '1996-02-28',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09191234567', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '11-2222-3333', 'phic_number' => 'PH888999', 'hdmf_number' => 'HDMF888999',
                'tin_number' => 'TIN888999', 'date_hired' => '2021-08-01',
                'date_regularized' => '2022-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT012', 'last_name' => 'Masabnig', 'first_name' => 'Marlou',
                'middle_name' => 'L.', 'gender' => 'Male', 'birth_date' => '1995-09-19',
                'age' => 30, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09192345678', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '22-3333-4444', 'phic_number' => 'PH999000', 'hdmf_number' => 'HDMF999000',
                'tin_number' => 'TIN999000', 'date_hired' => '2020-10-01',
                'date_regularized' => '2021-04-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT013', 'last_name' => 'Matuod', 'first_name' => 'Meinard',
                'middle_name' => 'M.', 'gender' => 'Male', 'birth_date' => '1997-05-07',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09193456789', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '33-4444-5555', 'phic_number' => 'PH000111', 'hdmf_number' => 'HDMF000111',
                'tin_number' => 'TIN000111', 'date_hired' => '2022-06-01',
                'date_regularized' => '2022-12-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT014', 'last_name' => 'Molina', 'first_name' => 'Emily',
                'middle_name' => 'N.', 'gender' => 'Female', 'birth_date' => '1999-11-11',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09194567890', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '44-5555-6666', 'phic_number' => 'PH111222', 'hdmf_number' => 'HDMF111222',
                'tin_number' => 'TIN111222', 'date_hired' => '2023-04-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT015', 'last_name' => 'Separa', 'first_name' => 'Catherine',
                'middle_name' => 'O.', 'gender' => 'Female', 'birth_date' => '1996-01-30',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Digos City',
                'contact_number' => '09195678901', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '55-6666-7777', 'phic_number' => 'PH222333', 'hdmf_number' => 'HDMF222333',
                'tin_number' => 'TIN222333', 'date_hired' => '2021-03-01',
                'date_regularized' => '2021-09-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT016', 'last_name' => 'Sumalinog', 'first_name' => 'Shiela',
                'middle_name' => 'P.', 'gender' => 'Female', 'birth_date' => '1998-04-16',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09196789012', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '66-7777-8888', 'phic_number' => 'PH333444', 'hdmf_number' => 'HDMF333444',
                'tin_number' => 'TIN333444', 'date_hired' => '2022-08-01',
                'date_regularized' => '2023-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT017', 'last_name' => 'Vios', 'first_name' => 'Christopher Dave',
                'middle_name' => 'Q.', 'gender' => 'Male', 'birth_date' => '1994-10-23',
                'age' => 31, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09197890123', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '77-8888-9999', 'phic_number' => 'PH444555', 'hdmf_number' => 'HDMF444555',
                'tin_number' => 'TIN444555', 'date_hired' => '2020-01-15',
                'date_regularized' => '2020-07-15', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT018', 'last_name' => 'Marquez', 'first_name' => 'Aeron',
                'middle_name' => 'R.', 'gender' => 'Male', 'birth_date' => '1997-08-08',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09198901234', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '88-9999-0000', 'phic_number' => 'PH555666', 'hdmf_number' => 'HDMF555666',
                'tin_number' => 'TIN555666', 'date_hired' => '2022-09-01',
                'date_regularized' => '2023-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT019', 'last_name' => 'Rana', 'first_name' => 'Rene',
                'middle_name' => 'S.', 'gender' => 'Male', 'birth_date' => '1995-03-12',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Tagum City',
                'contact_number' => '09199012345', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '99-0000-1111', 'phic_number' => 'PH666777', 'hdmf_number' => 'HDMF666777',
                'tin_number' => 'TIN666777', 'date_hired' => '2021-02-01',
                'date_regularized' => '2021-08-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TNT020', 'last_name' => 'Atacador', 'first_name' => 'Marylyn',
                'middle_name' => 'T.', 'gender' => 'Female', 'birth_date' => '1999-06-25',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09190123456', 'company_id' => $companyIds['Tom N Toms'],
                'department_id' => $departmentIds['Cashier Team'],
                'position_id' => $positionIds['Cashier'], 'account_id' => null,
                'sss_number' => '10-1111-2222', 'phic_number' => 'PH777888', 'hdmf_number' => 'HDMF777888',
                'tin_number' => 'TIN777888', 'date_hired' => '2023-05-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // TechHub (20 employees)
            // TechHub (20 employees)
            [
                'id_number' => 'TH001', 'last_name' => 'Andres', 'first_name' => 'Mabelle',
                'middle_name' => 'A.', 'gender' => 'Female', 'birth_date' => '1999-01-15',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09998887777', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '44-5555-6666', 'phic_number' => 'PH222333', 'hdmf_number' => 'HDMF222333',
                'tin_number' => 'TIN222333', 'date_hired' => '2022-09-01',
                'date_regularized' => '2023-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH002', 'last_name' => 'Saliot', 'first_name' => 'Shaina',
                'middle_name' => 'B.', 'gender' => 'Female', 'birth_date' => '1994-02-18',
                'age' => 31, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09175551234', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '55-6666-7777', 'phic_number' => 'PH444555', 'hdmf_number' => 'HDMF444555',
                'tin_number' => 'TIN444555', 'date_hired' => '2020-05-01',
                'date_regularized' => '2020-11-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH003', 'last_name' => 'Navarro', 'first_name' => 'Mary Rose',
                'middle_name' => 'C.', 'gender' => 'Female', 'birth_date' => '1997-07-22',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09176667890', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['IT'],
                'position_id' => $positionIds['Team Lead'], 'account_id' => null,
                'sss_number' => '66-7777-8888', 'phic_number' => 'PH666777', 'hdmf_number' => 'HDMF666777',
                'tin_number' => 'TIN666777', 'date_hired' => '2019-04-15',
                'date_regularized' => '2019-10-15', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH004', 'last_name' => 'Mc Aljas', 'first_name' => 'Jhon',
                'middle_name' => 'D.', 'gender' => 'Male', 'birth_date' => '1992-12-05',
                'age' => 33, 'civil_status' => 'Married', 'address' => 'Davao del Sur',
                'contact_number' => '09177778888', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '77-8888-9999', 'phic_number' => 'PH888999', 'hdmf_number' => 'HDMF888999',
                'tin_number' => 'TIN888999', 'date_hired' => '2021-02-01',
                'date_regularized' => '2021-08-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH005', 'last_name' => 'Miranda', 'first_name' => 'Marion',
                'middle_name' => 'E.', 'gender' => 'Female', 'birth_date' => '2000-06-17',
                'age' => 25, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09179990000', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '88-9999-0000', 'phic_number' => 'PH000111', 'hdmf_number' => 'HDMF000111',
                'tin_number' => 'TIN000111', 'date_hired' => '2024-01-05',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH006', 'last_name' => 'Dela Cruz', 'first_name' => 'Kyla',
                'middle_name' => 'F.', 'gender' => 'Female', 'birth_date' => '1998-03-09',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09171112222', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '11-2222-3333', 'phic_number' => 'PH111222', 'hdmf_number' => 'HDMF111222',
                'tin_number' => 'TIN111222', 'date_hired' => '2022-07-01',
                'date_regularized' => '2023-01-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH007', 'last_name' => 'Dignadice', 'first_name' => 'Crystelle',
                'middle_name' => 'G.', 'gender' => 'Female', 'birth_date' => '1996-11-14',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09172223333', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '22-3333-4444', 'phic_number' => 'PH222333', 'hdmf_number' => 'HDMF222333',
                'tin_number' => 'TIN222333', 'date_hired' => '2021-04-01',
                'date_regularized' => '2021-10-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH008', 'last_name' => 'Romero', 'first_name' => 'Neil Vincent',
                'middle_name' => 'H.', 'gender' => 'Male', 'birth_date' => '1995-08-27',
                'age' => 30, 'civil_status' => 'Single', 'address' => 'Panabo City',
                'contact_number' => '09173334444', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['IT'],
                'position_id' => $positionIds['Team Lead'], 'account_id' => null,
                'sss_number' => '33-4444-5555', 'phic_number' => 'PH333444', 'hdmf_number' => 'HDMF333444',
                'tin_number' => 'TIN333444', 'date_hired' => '2020-03-01',
                'date_regularized' => '2020-09-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH009', 'last_name' => 'Agapay', 'first_name' => 'Rey Mart',
                'middle_name' => 'I.', 'gender' => 'Male', 'birth_date' => '1997-05-19',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09174445555', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '44-5555-6666', 'phic_number' => 'PH444555', 'hdmf_number' => 'HDMF444555',
                'tin_number' => 'TIN444555', 'date_hired' => '2022-10-01',
                'date_regularized' => '2023-04-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH010', 'last_name' => 'Gastones', 'first_name' => 'Esther',
                'middle_name' => 'J.', 'gender' => 'Female', 'birth_date' => '1999-02-03',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09175556666', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '55-6666-7777', 'phic_number' => 'PH555666', 'hdmf_number' => 'HDMF555666',
                'tin_number' => 'TIN555666', 'date_hired' => '2023-06-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH011', 'last_name' => 'Yap', 'first_name' => 'Maverick',
                'middle_name' => 'K.', 'gender' => 'Male', 'birth_date' => '1994-09-12',
                'age' => 31, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09176667777', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '66-7777-8888', 'phic_number' => 'PH666777', 'hdmf_number' => 'HDMF666777',
                'tin_number' => 'TIN666777', 'date_hired' => '2021-05-01',
                'date_regularized' => '2021-11-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH012', 'last_name' => 'Baynosa', 'first_name' => 'Junnel',
                'middle_name' => 'L.', 'gender' => 'Male', 'birth_date' => '1998-12-28',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09177778888', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '77-8888-9999', 'phic_number' => 'PH777888', 'hdmf_number' => 'HDMF777888',
                'tin_number' => 'TIN777888', 'date_hired' => '2022-11-01',
                'date_regularized' => '2023-05-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH013', 'last_name' => 'Lagrimas', 'first_name' => 'Harold',
                'middle_name' => 'M.', 'gender' => 'Male', 'birth_date' => '1996-04-06',
                'age' => 29, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09178889999', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '88-9999-0000', 'phic_number' => 'PH888999', 'hdmf_number' => 'HDMF888999',
                'tin_number' => 'TIN888999', 'date_hired' => '2021-08-01',
                'date_regularized' => '2022-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH014', 'last_name' => 'Madulara', 'first_name' => 'Marvin',
                'middle_name' => 'N.', 'gender' => 'Male', 'birth_date' => '1993-07-21',
                'age' => 32, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09179990001', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['IT'],
                'position_id' => $positionIds['Team Lead'], 'account_id' => null,
                'sss_number' => '99-0000-1111', 'phic_number' => 'PH999000', 'hdmf_number' => 'HDMF999000',
                'tin_number' => 'TIN999000', 'date_hired' => '2019-06-01',
                'date_regularized' => '2019-12-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH015', 'last_name' => 'Badilles', 'first_name' => 'Karlo',
                'middle_name' => 'O.', 'gender' => 'Male', 'birth_date' => '1997-10-15',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09171112223', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '10-1111-2222', 'phic_number' => 'PH000111', 'hdmf_number' => 'HDMF000111',
                'tin_number' => 'TIN000111', 'date_hired' => '2022-12-01',
                'date_regularized' => '2023-06-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH016', 'last_name' => 'Fernandez', 'first_name' => 'Ana',
                'middle_name' => 'P.', 'gender' => 'Female', 'birth_date' => '1995-01-24',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Digos City',
                'contact_number' => '09172223334', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '11-2222-3334', 'phic_number' => 'PH111223', 'hdmf_number' => 'HDMF111223',
                'tin_number' => 'TIN111223', 'date_hired' => '2020-08-01',
                'date_regularized' => '2021-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH017', 'last_name' => 'Jainar', 'first_name' => 'Hayde',
                'middle_name' => 'Q.', 'gender' => 'Female', 'birth_date' => '1999-05-08',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09173334445', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '22-3333-4445', 'phic_number' => 'PH222334', 'hdmf_number' => 'HDMF222334',
                'tin_number' => 'TIN222334', 'date_hired' => '2023-07-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH018', 'last_name' => 'Canlas', 'first_name' => 'Charity Jaine',
                'middle_name' => 'R.', 'gender' => 'Female', 'birth_date' => '1998-08-18',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09174445556', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '33-4444-5556', 'phic_number' => 'PH333445', 'hdmf_number' => 'HDMF333445',
                'tin_number' => 'TIN333445', 'date_hired' => '2022-03-01',
                'date_regularized' => '2022-09-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH019', 'last_name' => 'Mabatuan', 'first_name' => 'Liezel',
                'middle_name' => 'S.', 'gender' => 'Female', 'birth_date' => '1996-12-11',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09175556667', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['eBay Escalations'],
                'sss_number' => '44-5555-6667', 'phic_number' => 'PH444556', 'hdmf_number' => 'HDMF444556',
                'tin_number' => 'TIN444556', 'date_hired' => '2021-09-01',
                'date_regularized' => '2022-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'TH020', 'last_name' => 'Pacatang', 'first_name' => 'Brent',
                'middle_name' => 'T.', 'gender' => 'Male', 'birth_date' => '1994-03-29',
                'age' => 31, 'civil_status' => 'Single', 'address' => 'Panabo City',
                'contact_number' => '09176667778', 'company_id' => $companyIds['TechHub'],
                'department_id' => $departmentIds['Customer Support'],
                'position_id' => $positionIds['CSR'], 'account_id' => $accountIds['Amazon Support'],
                'sss_number' => '55-6666-7778', 'phic_number' => 'PH555667', 'hdmf_number' => 'HDMF555667',
                'tin_number' => 'TIN555667', 'date_hired' => '2020-10-01',
                'date_regularized' => '2021-04-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // SteamTrain (20 employees)
            [
                'id_number' => 'ST001', 'last_name' => 'Paligutan', 'first_name' => 'Brando',
                'middle_name' => 'A.', 'gender' => 'Male', 'birth_date' => '1995-03-12',
                'age' => 30, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09181110001', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '66-7777-8889', 'phic_number' => 'PH666778', 'hdmf_number' => 'HDMF666778',
                'tin_number' => 'TIN666778', 'date_hired' => '2021-06-01',
                'date_regularized' => '2021-12-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST002', 'last_name' => 'Tan', 'first_name' => 'Jane Zeneth',
                'middle_name' => 'B.', 'gender' => 'Female', 'birth_date' => '1998-06-25',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09182220002', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '77-8888-9990', 'phic_number' => 'PH777889', 'hdmf_number' => 'HDMF777889',
                'tin_number' => 'TIN777889', 'date_hired' => '2022-08-01',
                'date_regularized' => '2023-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST003', 'last_name' => 'Pogoy', 'first_name' => 'Rochelle Mae',
                'middle_name' => 'C.', 'gender' => 'Female', 'birth_date' => '2000-09-08',
                'age' => 25, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09183330003', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '88-9999-0001', 'phic_number' => 'PH888990', 'hdmf_number' => 'HDMF888990',
                'tin_number' => 'TIN888990', 'date_hired' => '2024-02-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST004', 'last_name' => 'Tañan', 'first_name' => 'Michael James',
                'middle_name' => 'D.', 'gender' => 'Male', 'birth_date' => '1996-11-17',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09184440004', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '99-0000-1112', 'phic_number' => 'PH999001', 'hdmf_number' => 'HDMF999001',
                'tin_number' => 'TIN999001', 'date_hired' => '2021-10-01',
                'date_regularized' => '2022-04-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST005', 'last_name' => 'Cumawas', 'first_name' => 'Realyn',
                'middle_name' => 'E.', 'gender' => 'Female', 'birth_date' => '1999-04-21',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09185550005', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '10-1111-2223', 'phic_number' => 'PH000112', 'hdmf_number' => 'HDMF000112',
                'tin_number' => 'TIN000112', 'date_hired' => '2023-01-01',
                'date_regularized' => '2023-07-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST006', 'last_name' => 'Gavino', 'first_name' => 'Queen Crystal',
                'middle_name' => 'F.', 'gender' => 'Female', 'birth_date' => '1997-07-14',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09186660006', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '11-2222-3335', 'phic_number' => 'PH111224', 'hdmf_number' => 'HDMF111224',
                'tin_number' => 'TIN111224', 'date_hired' => '2022-05-01',
                'date_regularized' => '2022-11-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST007', 'last_name' => 'Mallari', 'first_name' => 'Akira',
                'middle_name' => 'G.', 'gender' => 'Female', 'birth_date' => '1995-12-03',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09187770007', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '22-3333-4446', 'phic_number' => 'PH222335', 'hdmf_number' => 'HDMF222335',
                'tin_number' => 'TIN222335', 'date_hired' => '2020-07-01',
                'date_regularized' => '2021-01-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST008', 'last_name' => 'Cid', 'first_name' => 'Emile Elisha',
                'middle_name' => 'H.', 'gender' => 'Female', 'birth_date' => '1998-02-19',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09188880008', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '33-4444-5557', 'phic_number' => 'PH333446', 'hdmf_number' => 'HDMF333446',
                'tin_number' => 'TIN333446', 'date_hired' => '2022-09-01',
                'date_regularized' => '2023-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST009', 'last_name' => 'Bultron', 'first_name' => 'Jay-Ann',
                'middle_name' => 'I.', 'gender' => 'Female', 'birth_date' => '2000-05-26',
                'age' => 25, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09189990009', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '44-5555-6668', 'phic_number' => 'PH444557', 'hdmf_number' => 'HDMF444557',
                'tin_number' => 'TIN444557', 'date_hired' => '2023-11-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST010', 'last_name' => 'Gambot', 'first_name' => 'Florecel Gwen',
                'middle_name' => 'J.', 'gender' => 'Female', 'birth_date' => '1996-08-10',
                'age' => 29, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09180001110', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '55-6666-7779', 'phic_number' => 'PH555668', 'hdmf_number' => 'HDMF555668',
                'tin_number' => 'TIN555668', 'date_hired' => '2021-12-01',
                'date_regularized' => '2022-06-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST011', 'last_name' => 'Pag-usara', 'first_name' => 'Lorrhea Alexa',
                'middle_name' => 'K.', 'gender' => 'Female', 'birth_date' => '1999-01-28',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09181112221', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '66-7777-8890', 'phic_number' => 'PH666779', 'hdmf_number' => 'HDMF666779',
                'tin_number' => 'TIN666779', 'date_hired' => '2023-04-01',
                'date_regularized' => '2023-10-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST012', 'last_name' => 'Laurente', 'first_name' => 'Earl James',
                'middle_name' => 'L.', 'gender' => 'Male', 'birth_date' => '1997-10-05',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09182223332', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '77-8888-9991', 'phic_number' => 'PH777890', 'hdmf_number' => 'HDMF777890',
                'tin_number' => 'TIN777890', 'date_hired' => '2022-06-01',
                'date_regularized' => '2022-12-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST013', 'last_name' => 'Amora', 'first_name' => 'Deo',
                'middle_name' => 'M.', 'gender' => 'Male', 'birth_date' => '1994-04-13',
                'age' => 31, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09183334443', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '88-9999-0002', 'phic_number' => 'PH888991', 'hdmf_number' => 'HDMF888991',
                'tin_number' => 'TIN888991', 'date_hired' => '2020-11-01',
                'date_regularized' => '2021-05-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST014', 'last_name' => 'Calumpang', 'first_name' => 'Kirsten',
                'middle_name' => 'N.', 'gender' => 'Female', 'birth_date' => '1998-07-20',
                'age' => 27, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09184445554', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '99-0000-1113', 'phic_number' => 'PH999002', 'hdmf_number' => 'HDMF999002',
                'tin_number' => 'TIN999002', 'date_hired' => '2022-10-01',
                'date_regularized' => '2023-04-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST015', 'last_name' => 'Almaden', 'first_name' => 'Armeianne Charyl',
                'middle_name' => 'O.', 'gender' => 'Female', 'birth_date' => '2000-11-09',
                'age' => 25, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09185556665', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '10-1111-2224', 'phic_number' => 'PH000113', 'hdmf_number' => 'HDMF000113',
                'tin_number' => 'TIN000113', 'date_hired' => '2024-03-01',
                'date_regularized' => null, 'employment_status' => 'Probationary',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST016', 'last_name' => 'Leparto', 'first_name' => 'Joel',
                'middle_name' => 'P.', 'gender' => 'Male', 'birth_date' => '1995-02-16',
                'age' => 30, 'civil_status' => 'Married', 'address' => 'Panabo City',
                'contact_number' => '09186667776', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '11-2222-3336', 'phic_number' => 'PH111225', 'hdmf_number' => 'HDMF111225',
                'tin_number' => 'TIN111225', 'date_hired' => '2021-08-01',
                'date_regularized' => '2022-02-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST017', 'last_name' => 'Santos', 'first_name' => 'Rosa',
                'middle_name' => 'Q.', 'gender' => 'Female', 'birth_date' => '1999-06-23',
                'age' => 26, 'civil_status' => 'Single', 'address' => 'Davao City',
                'contact_number' => '09187778887', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '22-3333-4447', 'phic_number' => 'PH222336', 'hdmf_number' => 'HDMF222336',
                'tin_number' => 'TIN222336', 'date_hired' => '2023-05-01',
                'date_regularized' => '2023-11-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST018', 'last_name' => 'Mendoza', 'first_name' => 'Luis',
                'middle_name' => 'R.', 'gender' => 'Male', 'birth_date' => '1996-09-30',
                'age' => 29, 'civil_status' => 'Single', 'address' => 'Digos City',
                'contact_number' => '09188889998', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '33-4444-5558', 'phic_number' => 'PH333447', 'hdmf_number' => 'HDMF333447',
                'tin_number' => 'TIN333447', 'date_hired' => '2022-04-01',
                'date_regularized' => '2022-10-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST019', 'last_name' => 'Rivera', 'first_name' => 'Carmen',
                'middle_name' => 'S.', 'gender' => 'Female', 'birth_date' => '1993-12-07',
                'age' => 32, 'civil_status' => 'Married', 'address' => 'Davao City',
                'contact_number' => '09189990019', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '44-5555-6669', 'phic_number' => 'PH444558', 'hdmf_number' => 'HDMF444558',
                'tin_number' => 'TIN444558', 'date_hired' => '2020-09-01',
                'date_regularized' => '2021-03-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_number' => 'ST020', 'last_name' => 'Ramirez', 'first_name' => 'Diego',
                'middle_name' => 'T.', 'gender' => 'Male', 'birth_date' => '1997-03-18',
                'age' => 28, 'civil_status' => 'Single', 'address' => 'Tagum City',
                'contact_number' => '09180002220', 'company_id' => $companyIds['SteamTrain'],
                'department_id' => $departmentIds['Barista Team'],
                'position_id' => $positionIds['Barista'], 'account_id' => null,
                'sss_number' => '55-6666-7780', 'phic_number' => 'PH555669', 'hdmf_number' => 'HDMF555669',
                'tin_number' => 'TIN555669', 'date_hired' => '2022-07-01',
                'date_regularized' => '2023-01-01', 'employment_status' => 'Regular',
                'remarks' => null, 'date_separated' => null, 'profile_picture' => null,
                'created_at' => now(), 'updated_at' => now(),
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}
